services:
  postgres:
    image: postgres:16
    container_name: board_tpl_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: board_tpl
      POSTGRES_USER: board_tpl_user
      POSTGRES_PASSWORD: board_tpl_password
    ports:
      - "5432:5432"
    volumes:
      - board_tpl_pg_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:26.5.2
    container_name: board_tpl_keycloak
    restart: unless-stopped
    command:
      - start-dev
      - --import-realm
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: "true"
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak/import:/opt/keycloak/data/import:ro

volumes:
  board_tpl_pg_data:
